version: "3"

services:
  services:
    image: ${DOCKER_REGISTRY}/hm-services
    hostname: services
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DOMAIN=${DOMAIN}
      - DATABASE_URL=${DATABASE_URL}
      - IMAGE_STORAGE_BUCKET=${IMAGE_STORAGE_BUCKET}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_SECRET=${EMAIL_SECRET}
      - EMAIL_SENDER_ADDR=${EMAIL_SENDER_ADDR}
      - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
      - ACCOUNT_JWT_PRIVATE=${ACCOUNT_JWT_PRIVATE}
      - ACCOUNT_JWT_PUBLIC=${ACCOUNT_JWT_PUBLIC}
      - ACCOUNT_JWT_SECRET=${ACCOUNT_JWT_SECRET}
      - CLIENT_URL=${CLIENT_URL}
      # Match 06_load_parameter_store.sh
      - SECRET_DIR=/etc/hm-secrets
  bff:
    image: ${DOCKER_REGISTRY}/hm-bff
    hostname: bff
    ports:
      - "5000:5000"
    environment:
      - SERVICES_BASE_URL=http://services:3000
