version: "3"

services:
  services:
    image: ${DOCKER_REGISTRY}/hm-services
    hostname: services
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DOMAIN=${DOMAIN}
      - DATABASE_URL=${DATABASE_URL}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - ACCOUNT_JWT_PRIVATE=${ACCOUNT_JWT_PRIVATE}
      - ACCOUNT_JWT_PUBLIC=${ACCOUNT_JWT_PUBLIC}
      - ACCOUNT_JWT_SECRET=${ACCOUNT_JWT_SECRET}
      - ACCOUNT_RESET_PASSWORD_LINK=${ACCOUNT_RESET_PASSWORD_LINK}
  bff:
    image: ${DOCKER_REGISTRY}/hm-bff
    hostname: bff
    ports:
      - "5000:5000"
    environment:
      - SERVICES_BASE_URL="http://services:3000"
    