version: "3"

services:
  services:
    image: ${DOCKER_REGISTRY}/hm-services
    hostname: services
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DOMAIN=${DOMAIN}
      - DATABASE_URL=${DATABASE_URL}
      - SMTP_SERVICE=${SMTP_SERVICE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_SECRET=${SMTP_SECRET}
      - SMTP_SENDER_ADDR=${SMTP_SENDER_ADDR}
      - SMTP_SENDER_NAME=${SMTP_SENDER_NAME}
      - ACCOUNT_JWT_PRIVATE=${ACCOUNT_JWT_PRIVATE}
      - ACCOUNT_JWT_PUBLIC=${ACCOUNT_JWT_PUBLIC}
      - ACCOUNT_JWT_SECRET=${ACCOUNT_JWT_SECRET}
      - ACCOUNT_RESET_PASSWORD_LINK=${ACCOUNT_RESET_PASSWORD_LINK}
      # Match 06_load_parameter_store.sh
      - SECRET_DIR=/etc/hm-secrets
  bff:
    image: ${DOCKER_REGISTRY}/hm-bff
    hostname: bff
    ports:
      - "5000:5000"
    environment:
      - SERVICES_BASE_URL=http://services:3000
    