version: "3"

services:
  account:
    image: ${DOCKER_REGISTRY}/hm-account
    hostname: account
    ports:
      - "3010-3011:3010-3011"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DOMAIN=${DOMAIN}
      - ACCOUNT_JWT_PRIVATE=${ACCOUNT_JWT_PRIVATE}
      - ACCOUNT_JWT_SECRET=${ACCOUNT_JWT_SECRET}
      - ACCOUNT_PORT=${ACCOUNT_PORT}
      - ACCOUNT_PRIVATE_PORT=${ACCOUNT_PRIVATE_PORT}
      - ACCOUNT_PRIVATE_HOST=${ACCOUNT_PRIVATE_HOST}
  core:
    image: ${DOCKER_REGISTRY}/hm-core
    hostname: core
    ports:
      - "3020-3021:3020-3021"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DOMAIN=${DOMAIN}
      - ACCOUNT_JWT_PUBLIC=${ACCOUNT_JWT_PUBLIC}
      - ACCOUNT_PRIVATE_PORT=${ACCOUNT_PRIVATE_PORT}
      - ACCOUNT_PRIVATE_HOST=${ACCOUNT_PRIVATE_HOST}
      - CORE_PORT=${CORE_PORT}
      - CORE_PRIVATE_PORT=${CORE_PRIVATE_PORT}
  bff:
    image: ${DOCKER_REGISTRY}/hm-bff
    hostname: bff
    ports:
      - "5000:5000"
    environment:
      - ACCOUNT_BASE_URL="account:3010"
      - CORE_BASE_URL="core:3020"
    