version: "3"

services:
  account:
    image: ${DOCKER_REGISTRY}/hm-account
    hostname: account
    ports:
      - "5000:3010"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCOUNT_JWT_PRIVATE=${ACCOUNT_JWT_PRIVATE}
      - ACCOUNT_JWT_PUBLIC=${ACCOUNT_JWT_PUBLIC}
      - ACCOUNT_JWT_SECRET=${ACCOUNT_JWT_SECRET}
      - ACCOUNT_PORT=${ACCOUNT_PORT}
      - ACCOUNT_PRIVATE_PORT=${ACCOUNT_PRIVATE_PORT}
      - ACCOUNT_PRIVATE_HOST=${ACCOUNT_PRIVATE_HOST}
  # core:
  #   image: ${DOCKER_REGISTRY}/hm-core
  #   hostname: core
  #   ports:
  #     - "3020-3021:3020-3021"
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - ACCOUNT_JWT_PUBLIC=${ACCOUNT_JWT_PUBLIC}
  #     - ACCOUNT_PRIVATE_PORT=${ACCOUNT_PRIVATE_PORT}
  #     - ACCOUNT_PRIVATE_HOST=${ACCOUNT_PRIVATE_HOST}
  #     - CORE_PORT=${CORE_PORT}
  #     - CORE_PRIVATE_PORT=${CORE_PRIVATE_PORT}
  # nginx:
  #   image: nginx:stable-alpine
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - account
  #     - core
