version: "3"

services:
  account:
    image: ${DOCKER_REGISTRY}/hm-account
    hostname: account
    ports:
      - "3010-3011:3010-3011"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DOMAIN=${DOMAIN}
      - ACCOUNT_JWT_PRIVATE=${ACCOUNT_JWT_PRIVATE}
      - ACCOUNT_JWT_SECRET=${ACCOUNT_JWT_SECRET}
      - ACCOUNT_PORT=${ACCOUNT_PORT}
      - ACCOUNT_PRIVATE_PORT=${ACCOUNT_PRIVATE_PORT}
      - ACCOUNT_PRIVATE_HOST=${ACCOUNT_PRIVATE_HOST}
  # core:
  #   image: ${DOCKER_REGISTRY}/hm-core
  #   hostname: core
  #   ports:
  #     - "3020-3021:3020-3021"
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - DOMAIN=${DOMAIN}
  #     - ACCOUNT_JWT_PUBLIC=${ACCOUNT_JWT_PUBLIC}
  #     - ACCOUNT_PRIVATE_PORT=${ACCOUNT_PRIVATE_PORT}
  #     - ACCOUNT_PRIVATE_HOST=${ACCOUNT_PRIVATE_HOST}
  #     - CORE_PORT=${CORE_PORT}
  #     - CORE_PRIVATE_PORT=${CORE_PRIVATE_PORT}
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    # restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${EC2_CERTBOT_DIR}:${EC2_CERTBOT_DIR}
      - ${EC2_CERTBOT_BACKUP_DIR}:${EC2_CERTBOT_BACKUP_DIR}
      - ${EFS_BASE_CERTBOT_DIR}:${EFS_BASE_CERTBOT_DIR}
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      # For hardcoded path in nginx.conf
      - ./certbot/conf/live/${DOMAIN}:/etc/ssl/certbot
      # For Elastic Beanstalk logging
      - /var/log/nginx:/var/log/nginx
      - /var/log/letsencrypt:/var/log/letsencrypt
    environment:
      - DOMAIN=${DOMAIN}
      - EC2_CERTBOT_DIR=${EC2_CERTBOT_DIR}
      - EC2_CERTBOT_BACKUP_DIR=${EC2_CERTBOT_BACKUP_DIR}
      - EFS_BASE_CERTBOT_DIR=${EFS_BASE_CERTBOT_DIR}
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    depends_on:
      - account
    #   - core
  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    environment:
      - DOMAIN=${DOMAIN}
      - EC2_CERTBOT_DIR=${EC2_CERTBOT_DIR}
      - EC2_CERTBOT_BACKUP_DIR=${EC2_CERTBOT_BACKUP_DIR}
      - EFS_BASE_CERTBOT_DIR=${EFS_BASE_CERTBOT_DIR}
    depends_on:
      - nginx